In [3]:
mass_point = 'NMSSM_XToYHTo6B_MX-700_MY-400_TuneCP5_13TeV-madgraph-pythia8'
f_dir = f'/eos/uscms/store/user/srosenzw/sixb/ntuples/Summer2018UL/maxbtag_4b/Official_NMSSM/syst/systematic/up/{mass_point}/ntuple.root'
model_dir = f'/eos/uscms/store/user/srosenzw/weaver/models/exp_sixb_official/feynnet_ranker_6b/20230731_7d266883bbfb88fe4e226783a7d1c9db_ranger_lr0.0047_batch2000_withbkg/predict_output/2018/systematic_up_{mass_point}.root'
# FlavorQCD = SixB(f_dir.replace('systematic', 'FlavorQCD'), feyn=model_dir.replace('systematic', 'FlavorQCD'))
Absolute = SixB(f_dir.replace('systematic', 'Absolute'), feyn=model_dir.replace('systematic', 'Absolute'))
nominal = SixB(f'/eos/uscms/store/user/srosenzw/sixb/ntuples/Summer2018UL/maxbtag_4b/Official_NMSSM/{mass_point}/ntuple.root')

[14:27:08] Loading                                                                                     ]8;id=412016;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py\signal.py]8;;\:]8;id=858641;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py#91\91]8;;\
           Summer2018UL/maxbtag_4b/Official_NMSSM/syst/Absolute/up/NMSSM_XToYHTo6B_MX-700_MY-400_TuneC             
           P5_13TeV-madgraph-pythia8/ntuple.root...                                                                

[14:27:13] Loading                                                                                    ]8;id=29775;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py\signal.py]8;;\:]8;id=836527;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py#185\185]8;;\
           /eos/uscms/store/user/srosenzw/weaver/models/exp_sixb_official/feynnet_ranker_6b/20230731_              
           7d266883bbfb88fe4e226783a7d1c9db_ranger_lr0.0047_batch2000_withbkg/predict_output/2018/Abs              
           olute_up_NMSSM_XToYHTo6B_MX-700_MY-400_TuneCP5_13TeV-madgraph-pythia8.root...                           

[14:27:18] Loading                                                                                     ]8;id=801439;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py\signal.py]8;;\:]8;id=789052;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py#91\91]8;;\
           Summer2018UL/maxbtag_4b/Official_NMSSM/NMSSM_XToYHTo6B_MX-700_MY-400_TuneCP5_13TeV-madgraph             
           -pythia8/ntuple.root...                                                                                 

[14:27:23] Loading                                                                                    ]8;id=701315;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py\signal.py]8;;\:]8;id=892668;file:///uscms_data/d3/srosenzw/workarea/higgs/sixb_analysis/CMSSW_10_6_19_patch2/src/sixb/utils/analysis/signal.py#185\185]8;;\
           /eos/uscms/store/user/srosenzw/weaver/models/exp_sixb_official/feynnet_ranker_6b/20230731_              
           7d266883bbfb88fe4e226783a7d1c9db_ranger_lr0.0047_batch2000_withbkg/predict_output/2018/NMS              
           SM_XToYHTo6B_MX-700_MY-400_TuneCP5_13TeV-madgraph-pythia8.root...                                       

In [4]:
nominal.total, Absolute.total

(890000, 890000)

In [5]:
nominal.cutflow, Absolute.cutflow

(array([890000, 626022, 505446, 279122]),
 array([890000, 626022, 505518, 279162]))

In [17]:
nominal.bSFshape_up_jesFlavorQCD, FlavorQCD.bSFshape_up_jesFlavorQCD, HF.bSFshape_up_jesFlavorQCD

(<Array [0.705, 0.743, 0.662, ..., 0.986, 1.22, 0.811] type='279122 * float64'>,
 <Array [0.705, 0.743, 0.662, ..., 0.986, 1.22, 0.811] type='213150 * float64'>,
 <Array [0.705, 0.743, 0.662, ..., 1.22, 0.698, 0.984] type='222328 * float64'>)

In [18]:
nominal.bSFshape_up_jesHF, FlavorQCD.bSFshape_up_jesHF, HF.bSFshape_up_jesHF

(<Array [0.71, 0.735, 0.619, ..., 0.987, 1.19, 0.831] type='279122 * float64'>,
 <Array [0.71, 0.735, 0.619, ..., 0.987, 1.19, 0.831] type='213150 * float64'>,
 <Array [0.71, 0.735, 0.619, 1.06, ..., 1.22, 0.708, 1] type='222328 * float64'>)

In [25]:
nominal.total, FlavorQCD.total

(890000, 264000)

In [33]:
len(FlavorQCD.n_jet)

213150

In [3]:
FlavorQCD.cutflow, nominal.cutflow

(array([890000, 626022, 505506, 279145]),
 array([890000, 626022, 505446, 279122]))

In [28]:
FlavorQCD.cutflow/FlavorQCD.cutflow[0], nominal.cutflow/nominal.cutflow[0]

(array([1.        , 0.70189015, 0.56653409, 0.313125  ]),
 array([1.        , 0.70339551, 0.56791685, 0.31362022]))

In [19]:
nominal.bSFshape_up_jesHF_raw, FlavorQCD.bSFshape_up_jesHF_raw, HF.bSFshape_up_jesHF_raw

(<Array [0.718, 0.7, 0.589, ..., 0.938, 1.25, 0.813] type='279122 * float32'>,
 <Array [0.718, 0.7, 0.589, ..., 0.938, 1.25, 0.813] type='213150 * float32'>,
 <Array [0.718, 0.7, 0.589, ..., 1.15, 0.67, 0.966] type='222328 * float32'>)

In [4]:
FlavorQCD.scale, nominal.scale

(0.020137078651685392, 0.020137078651685392)

In [5]:
len(FlavorQCD.X.m), len(nominal.X.m)

(279145, 279122)

In [7]:
fig, ax = plt.subplots()

mBins = np.linspace(375,1500,31)
n = Hist(nominal.X.m, bins=mBins, weights=nominal.scale*nominal.bSFshape_central, ax=ax)
# n = Hist(nominal.X.m, bins=mBins, weights=nominal.scale*nominal.bSFshape_up_jesFlavorQCD, ax=ax)
n = Hist(Absolute.X.m, bins=mBins, weights=Absolute.scale*Absolute.bSFshape_up_jesAbsolute, ax=ax)