In [2]:
from myuproot import open_up

In [10]:
import awkward as ak

In [3]:
filename = f'../../signal/skimmed/NMSSM_XYH_YToHH_6b_MX_700_MY_400_testing_set_preselections.root'
tree, ak_table, np_table = open_up(filename)

-- [INFO] -- /uscms/home/srosenzw/nobackup/miniconda3/envs/work/lib/python3.8/runpy.py -- Opening ROOT file ../../signal/skimmed/NMSSM_XYH_YToHH_6b_MX_700_MY_400_testing_set_preselections.root with columns
----------------------------------------------------------------------------------------------------
                                            TABLE COLUMNS                                           
----------------------------------------------------------------------------------------------------
-- [INFO] -- /uscms/home/srosenzw/nobackup/miniconda3/envs/work/lib/python3.8/runpy.py -- Tree contains 105919 events.
Run                               LumiSec                           Event                             
n_other_pv                        rhofastjet_all                    gen_X_fc_m                        
gen_X_fc_pt                       gen_X_fc_eta                      gen_X_fc_phi                      
gen_X_m                           gen_X_pt                     

In [5]:
np_table['jet_signalId']

array([array([ 0,  4, -1,  3,  5, -1], dtype=int32),
       array([ 0,  4, -1,  1,  2,  5], dtype=int32),
       array([ 2,  4,  3,  1,  0, -1, -1], dtype=int32), ...,
       array([2, 0, 5, 4, 1, 3], dtype=int32),
       array([2, 3, 1, 0, 5, 4], dtype=int32),
       array([2, 4, 3, 1, 5, 0], dtype=int32)], dtype=object)

In [8]:
%matplotlib widget
import matplotlib.pyplot as plt

In [6]:
from consistent_plots import hist

In [12]:
fig, ax = plt.subplots()

hist(ax, ak.to_numpy(ak.flatten(ak_table['jet_signalId'])))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([ 98738.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0., 101777.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,  89382.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0., 101640.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,  89696.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,  97545.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
      